### PR TITLE
Update SETUP.md

### PR DESCRIPTION
**Pull request by SPDurkee**
Updated SETUP.md to include reference to the Smart Life app as well a cleaned instructions / setups.

### CODE REVIEW

**Comment by codetheweb** [comment]
I know the current contribution instructions say to make PRs against development, but master is more up to date. Sorry about that. Could you change the base branch to be master?

**Comment by codetheweb** [comment]
Closes #362.

**Comment by SPDurkee** [comment]
Shall I update CONTRIBUTING.md as well to indicate that the PR should be to the master branch? I'd like to expand step 7 as well detailing Commit, Push, and Open a PR...

**Comment by codetheweb** [comment]
Sure, that sounds great. Thanks!

**Pull request closed without merging**
