### PR TITLE
Bugfix undefined key fixing #217

### PR DESCRIPTION
**Pull request by kueblc**
Wouldn't be a proper release without an emergency patch!

### CODE REVIEW

**Comment by Apollon77** [comment]
LOL ;-)

**Comment by codetheweb** [comment]
Published.

**Comment by kueblc** [comment]
Sorry @codetheweb! :stuck_out_tongue:

Introduced in c4b20687ddae7b4658e8e0ddf3d93c9eaedcf737

Thanks for merging so quickly :smile:

**Comment by codetheweb** [comment]
No problem.

We'll have to add some more tests once we update @tuyapi/stub.

**Comment by kueblc** [comment]
Sounds good. Would be great to have more real world data samples in the tests.

**Pull request merged**
