### PR TITLE
Heartbeat event

### PR DESCRIPTION
**Pull request by ncovercash**
This PR adds an event which is emitted when the library receives a successful heartbeat.

I was not sure if the documentation should be generated as part of the PR or not, therefore, they are separate commits.

### CODE REVIEW

**Comment by ncovercash** [comment]
Whoops, dumb typo, too much in my head at once 🙃 

Working on adding a test.

**Comment by ncovercash** [comment]
There we go, all should be good now (and Coveralls is happy!)

**Comment by codetheweb** [comment]
Looks good!

Did you bump the version in `package.json` and forget to push it?  I'm fine changing the version myself, just confused why it changed in the docs and not in `package.json`.

**Comment by ncovercash** [comment]
From what I can see, when I forked master, the version was 5.2.1 and the docs had 5.2.0.  I didn't change anything in package.json, just ran the documentation command.

**Comment by codetheweb** [comment]
Ah, got it.  My bad.

**Comment by ncovercash** [comment]
No worries, I was confused too!  Thanks for the merge, glad I could contribute!

**Comment by codetheweb** [comment]
Released in v5.3.0.

**Pull request merged**
