### PR TITLE
bring back nodejs 6 compatibility

### LINKED ISSUE #95: Last update made minimum node to 8 :-(
Hey @codetheweb,

I just realized that the lastupdate made the minimum version to node 8. It is because of the use of "padStart" String function in the parser. maybe you want to re-add nodejs 6 by changing this code part?

Ingo

### PR DESCRIPTION
**Pull request by Apollon77**
Fixes #95

### CODE REVIEW

**Comment by codetheweb** [comment]
👍 

Travis CI actually only tests Node 8, I should change the config so it tests 6+.

**Comment by Apollon77** [comment]
I have tests for 6,8,10 for my projects.I think LTS versions are sufficient

**Comment by Apollon77** [comment]
Can you please add an info when npm is updated too so that I can update my project? Would be awesome

**Comment by codetheweb** [comment]
Tests now cover versions 6, 8, 10, and latest stable release.  What do you mean about NPM?

**Comment by Apollon77** [comment]
Info about npm release for the node-6 fix ;-)

**Comment by codetheweb** [comment]
Yep, sure. 😄

**Comment by codetheweb** [comment]
Published @3.1.1.

**Comment by Apollon77** [comment]
thx!

**Pull request merged**
