### PR TITLE
Command18 after ping via Option

### PR DESCRIPTION
**Pull request by markuslaube**
This update allows using the variable (issueRefreshOnPing = true) to send command 18 after each ping and then to query the status using get. Since there are now some devices that do not send updates by themselves.

### CODE REVIEW

**Review by codetheweb — CHANGES_REQUESTED** [review]
Looks good! Just need to add a note to the JSDoc too.

**Comment by markuslaube** [comment]
ihm not a developer I hope that's it this what's you mean ;)

**Comment by Apollon77** [comment]
One dumb question ... DIO we need the Ping at all when we send a real message? ;-)

**Comment by markuslaube** [comment]
> One dumb question ... DIO we need the Ping at all when we send a real message? ;-)

I have no idea :-O

**Comment by Apollon77** [comment]
... just question because the "Ping" is mainly there to make xure the connection stays open when I remember correctly ... wehen we now send other data it should have the same purpose ... but ok we also do not need to experiment that out ... ;-)

**Comment by markuslaube** [comment]
Hello @codetheweb ,

please can you say if the change on [docs/index.html]this what's you mean with "Just need to add a note to the JSDoc too." or is this a misunderstanding from me?

Thanks, Markus

**Review by codetheweb — APPROVED** [review]
Yep, thanks.

**Comment by codetheweb** [comment]
Released in v7.3.0.

**Pull request merged**
