### PR TITLE
Emit disconnected event when there's no heartbeat response

### PR DESCRIPTION
**Pull request by codetheweb**
Also adds a test to make sure it's possible to reconnect to a device after it goes offline.

### CODE REVIEW

**Comment by codetheweb** [comment]
@ddv were you able to test this yet?

**Comment by dvv** [comment]
@codetheweb Nope. I finally managed to flash them all with esphome.
Let us merge and see the feedback.
I'll publish the code I developed during tests before reflashing -- it may provide some ideas.

**Comment by dvv** [comment]
As promised: https://github.com/dvv/tuya-mqtt/blob/master/tuya.js#L166-L221

**Comment by codetheweb** [comment]
Published in v6.1.4.

**Pull request merged**
