### PR TITLE
* make sure to not resolve or reject twice in connect method

### PR DESCRIPTION
**Pull request by Apollon77**
fixes https://github.com/codetheweb/tuyapi/issues/429

### CODE REVIEW

**Comment by Apollon77** [comment]
@codetheweb thankl yiou for check and accept (and update package) ...

**Comment by codetheweb** [comment]
Thanks. :)

**Comment by codetheweb** [comment]
Released in v7.2.1.

**Comment by Apollon77** [comment]
Thank you!

**Pull request merged**
