### PR TITLE
allow overriding deviceId on set as 5.2.0 (and update package-lock)

### PR DESCRIPTION
**Pull request by Apollon77**
addresses #296

### CODE REVIEW

**Comment by kueblc** [comment]
LGTM :+1:

**Comment by Apollon77** [comment]
Update pushed

**Comment by codetheweb** [comment]
Looks good, thanks.  Resolves #296.

**Comment by codetheweb** [comment]
Published @5.2.1 (forgot to update docs first).

**Comment by Apollon77** [comment]
Thank you very much

**Pull request merged**
