### PR TITLE
catch errors from parser and emit error if needed

### LINKED ISSUE #101: Exceptions thrown by messageparser are not catch by main class
The messageparser class throws an error in parse if magic suffix or prefix do not match. This is ok, BUT the index.js need to catch the exception and emit an error event instead because else the exception is unhandled (and also not really catchable from outside) and so the whole application it is used crashs

### PR DESCRIPTION
**Pull request by Apollon77**
fixes #101

### CODE REVIEW

**Comment by Apollon77** [comment]
I prepared the PR in Github web only because do not have my working environment today. So please regenerate the doscs :-) thank you.

A fast release would be great. Thank you

**Comment by codetheweb** [comment]
👍 thanks.

**Comment by Apollon77** [comment]
Thank you again for an info on npm publish :-)

**Comment by codetheweb** [comment]
Just published @3.1.2. 😉

**Pull request merged**
